Feat/step01
eyabc/Springboot-study pull request #1
Opened 2020-05-18 10:52 UTC by eyabc

처음이라 도움을 받아서 진행을 해보았습니다
리뷰부탁드립니다!

2020-05-18 12:40 UTC, sieunkr requested changes
소스코드 커밋&푸쉬 전부 되었는지 확인 부탁드리며
혹시 빠진 코드 있는지 확인 부탁드릴게요!

2020-05-18 12:40 UTC, sieunkr commented on src/main/java/com/eyabc/springboot/adapter/NaverAdapter.java
> +    private final String clientId = NaverAdapterSecret.getClientID();
이 부분에서 오류가 발생을 해서, 애플리케이션 실행이 안되네요? ㅠㅠ
혹시, NaverAdapterSecret 가 아니라 NaverAdapterSecretTemplate 아닌가요? 

코드 한번 확인 부탁드릴게요!
빌드가 되는 완성 코드를 다시 올려주시면 좋을 것 같아요!!

2020-05-18 13:12 UTC, eyabc commented on src/main/java/com/eyabc/springboot/adapter/NaverAdapter.java
> +    private final String clientId = NaverAdapterSecret.getClientID();
넵 알겠습니다!

2020-05-18 13:38 UTC, sieunkr commented on src/main/java/com/eyabc/springboot/adapter/NaverAdapterSecret.java
> +public class NaverAdapterSecret {
아.. 혹시, 보안코드 때문에 ignore 처리하셨었나봐요?ㅠㅠ
일단, ClientID, ClientSecret 의 인증키는 개인정보(?) 이니깐..
외부에 공개 안되는게 좋겠네요. 

ClientID = "" 이런식으로 올려주시면 제가 알아서 봐볼게요!!

2020-05-18 13:38 UTC, sieunkr commented on src/main/java/com/eyabc/springboot/adapter/NaverAdapter.java
> +    public static class RestTemplate extends org.springframework.web.client.RestTemplate { }
별도의 컨피그 클래스 만들고 
@Configuration, @Bean 사용해서 개선해보시겠어요? 


@Configuration
public class RestTemplateConfig{

@Bean
public RestTemplate restTemplate() {
  new RestTemplate();
}

2020-05-18 13:40 UTC, eyabc commented on src/main/java/com/eyabc/springboot/adapter/NaverAdapterSecret.java
> +public class NaverAdapterSecret {
나중에 파기하면 되니깐 괜찮을거같아요~

2020-05-19 10:11 UTC, merged

2020-05-19 10:12 UTC, eyabc commented
리뷰 감사합니다~!!